#!/usr/bin/env node

/**
 * ⚡ CLI Demo Runner — Customer Support Verification Guard
 * Executes both naive (❌) and resilient (✅) scenarios side-by-side
 * and prints comparative ASCII tables with input token stats.
 *
 * Usage:
 *   node demo.js            # Run both scenarios
 *   node demo.js --naive    # Run naive only
 *   node demo.js --resilient # Run resilient only
 *
 * 🤖 Generated by: DeepSeek V4 Pro
 */

import { runScenario } from "./src/coordinator.js";
import * as naive from "./src/subagent-naive.js";
import * as resilient from "./src/subagent-resilient.js";
import { banner, hr, padRight, padLeft, formatCurrency, formatPercent, median } from "./src/utils.js";

const flag = process.argv[2];

const CYAN = "\x1b[36m";
const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const MAGENTA = "\x1b[35m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";

function printMetricRow(label, naiveVal, resilientVal, unit = "", better = "lower") {
  const nv = typeof naiveVal === "number" ? naiveVal.toFixed(2) : naiveVal;
  const rv = typeof resilientVal === "number" ? resilientVal.toFixed(2) : resilientVal;
  const lb = padRight(label, 28);
  const nb = padLeft(String(nv), 14);
  const rb = padLeft(String(rv), 14);
  const delta = better === "lower"
    ? (Number(naiveVal) - Number(resilientVal))
    : (Number(resilientVal) - Number(naiveVal));
  const deltaSign = delta > 0 && better === "higher" ? "+" : delta > 0 && better === "lower" ? "+" : "";
  const deltaStr = padLeft(`${deltaSign}${delta.toFixed(2)}${unit}`, 14);
  const icon = (better === "lower" && delta > 0) || (better === "higher" && delta > 0) ? "✅" : "—";
  console.log(`  ${lb} ${nb} ${rb} ${deltaStr}  ${icon}`);
}

async function main() {
  console.log(banner(`⚡ Customer Support Verification Guard ⚡`));
  console.log(`  🤖 Generated by: DeepSeek V4 Pro\n`);
  console.log(`  📐 Architecture: Programmatic Prerequisite Verification\n`);
  console.log(`  📊 Test Corpus: 25 requests (~12% skip get_customer)\n`);

  const shouldNaive = !flag || flag === "--naive";
  const shouldResilient = !flag || flag === "--resilient";

  let naiveRun = null;
  let resilientRun = null;

  if (shouldNaive) {
    console.log(`${RED}${BOLD}  ❌ RUNNING NAIVE SCENARIO...${RESET}`);
    naiveRun = await runScenario(naive, "❌ Naive (Anti-Pattern)");
    console.log(`${RED}  ✓ Naive run complete: ${naiveRun.metrics.success}/${naiveRun.metrics.total} success, ${naiveRun.metrics.misidentified} misidentified${RESET}\n`);
  }

  if (shouldResilient) {
    console.log(`${GREEN}${BOLD}  ✅ RUNNING RESILIENT SCENARIO...${RESET}`);
    resilientRun = await runScenario(resilient, "✅ Resilient (Answer)");
    console.log(`${GREEN}  ✓ Resilient run complete: ${resilientRun.metrics.success}/${resilientRun.metrics.total} success, ${resilientRun.metrics.misidentified} misidentified${RESET}\n`);
  }

  if (naiveRun && resilientRun) {
    const nm = naiveRun.metrics;
    const rm = resilientRun.metrics;

    console.log(`${CYAN}${BOLD}  ╔══════════════════════════════════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}${BOLD}  ║            📊 COMPARATIVE METRICS — Naive vs Resilient             ║${RESET}`);
    console.log(`${CYAN}${BOLD}  ╚══════════════════════════════════════════════════════════════════════╝${RESET}\n`);
    console.log(`  ${BOLD}${padRight("Metric", 28)} ${padLeft("❌ Naive", 14)} ${padLeft("✅ Resilient", 14)} ${padLeft("Δ Delta", 14)}  Result${RESET}`);
    console.log(`  ${hr("─", 70)}`);

    printMetricRow("📋 Total Requests", nm.total, rm.total, "", "higher");
    printMetricRow("✅ Successful Refunds", nm.success, rm.success, "", "higher");
    printMetricRow("❌ Failures", nm.failure, rm.failure, "", "lower");
    printMetricRow("⚠️  Misidentified Accounts", nm.misidentified, rm.misidentified, "", "lower");
    printMetricRow("🛡️ Blocked Actions", nm.blocked, rm.blocked, "", "higher");
    printMetricRow("💸 Total Token Cost", nm.tokenCost, rm.tokenCost, " tokens", "lower");
    printMetricRow("🔧 Coordinator Interventions", nm.interventions, rm.interventions, "", "lower");
    printMetricRow("⏱  Total Time", nm.totalTime.toFixed(0), rm.totalTime.toFixed(0), " ms", "lower");
    printMetricRow("📐 Avg Latency/Request", (nm.latencies.reduce((a,b)=>a+b,0)/nm.latencies.length), (rm.latencies.reduce((a,b)=>a+b,0)/rm.latencies.length), " ms", "lower");
    printMetricRow("📏 Median Latency", median(nm.latencies), median(rm.latencies), " ms", "lower");
    printMetricRow("🎯 Success Rate", formatPercent(nm.success, nm.total), formatPercent(rm.success, rm.total), "", "higher");

    console.log(`\n  ${hr("─", 70)}`);

    // ── Input Token Stats & Efficiency Scoreboard ──

    const naiveTokens = nm.tokenCost;
    const resilientTokens = rm.tokenCost;
    const tokenSavings = naiveTokens - resilientTokens;
    const tokenReduction = ((tokenSavings / naiveTokens) * 100).toFixed(1);

    console.log(`\n${YELLOW}${BOLD}  ╔══════════════════════════════════════════════════════════════════════╗${RESET}`);
    console.log(`${YELLOW}${BOLD}  ║        📊 INPUT TOKEN STATS & EFFICIENCY SCOREBOARD 📊             ║${RESET}`);
    console.log(`${YELLOW}${BOLD}  ╚══════════════════════════════════════════════════════════════════════╝${RESET}\n`);
    console.log(`  ${BOLD}  🏷  Strategy                    │ Input Tokens │ Overhead │ Savings${RESET}`);
    console.log(`  ${hr("─", 64)}`);
    console.log(`  ${RED}  ❌ Naive (prompt-based guard)   │ ${padLeft(String(naiveTokens), 10)}   │ ${padLeft(String(nm.interventions + 1), 7)}   │   —    ${RESET}`);
    console.log(`  ${GREEN}  ✅ Resilient (programmatic guard)│ ${padLeft(String(resilientTokens), 10)}   │ ${padLeft(String(rm.interventions), 7)}   │ ${tokenReduction}%  ${RESET}`);
    console.log(`\n  ${YELLOW}  💡 Token Savings: ${tokenSavings} tokens (${tokenReduction}% reduction)${RESET}`);
    console.log(`  ${YELLOW}  🛡️ Misidentified Refunds Eliminated: ${nm.misidentified} → ${rm.misidentified}${RESET}`);
    console.log(`  ${YELLOW}  ⚡ Coordinator Overhead Reduction: ${nm.interventions} → ${rm.interventions}${RESET}`);
    console.log(`\n  ${MAGENTA}  📐 Why? Programmatic prerequisites prevent the LLM from${RESET}`);
    console.log(`  ${MAGENTA}     bypassing behavioral prompts. Enforced at runtime layer.${RESET}`);

    // ── Failure Analysis ──
    console.log(`\n${BOLD}  🔍 FAILURE ANALYSIS — Naive Misidentified Accounts:${RESET}`);
    const misidentified = naiveRun.results.filter(r => r.result.details.misidentified);
    for (const m of misidentified) {
      console.log(`${RED}     ❌ "${m.input.customerName}" → ${m.result.message}${RESET}`);
    }
    if (misidentified.length === 0) {
      console.log(`  ${GREEN}     (none in this run — 12% stochastic)${RESET}`);
    }

    console.log(`\n${BOLD}  🔍 SUCCESS ANALYSIS — Resilient Blocked Attempts:${RESET}`);
    const blocked = resilientRun.results.filter(r => r.result.message.includes("Blocked") || r.result.details.error === "VerificationRequiredError");
    for (const b of blocked) {
      console.log(`${GREEN}     🛡️ "${b.input.customerName}" → ${b.result.message}${RESET}`);
    }
    if (blocked.length === 0) {
      console.log(`  ${GREEN}     (all requests passed verification)${RESET}`);
    }
    console.log("");

    // ── Verdict ──
    if (nm.misidentified > 0 && rm.misidentified === 0) {
      console.log(`${GREEN}${BOLD}  🎯 VERDICT: The resilient architecture ELIMINATED all misidentified${RESET}`);
      console.log(`${GREEN}${BOLD}     account refunds that the naive approach allowed through.${RESET}`);
      console.log(`${GREEN}${BOLD}     Programmatic prerequisites >> Prompt-based guardrails.${RESET}\n`);
    }
  }

  console.log(`  ${CYAN}🤖 Generated by: DeepSeek V4 Pro${RESET}`);
  console.log(`  ${CYAN}🔗 https://github.com/rifaterdemsahin/customer-support-verification-guard${RESET}\n`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
