/**
 * @fileoverview 🔊 Web Speech API Narration Scripts
 * Each entry: text, selector, durationMs (approximate)
 * Used by both index.html GSAP timeline and Remotion audio sync.
 *
 * 🤖 Generated by: DeepSeek V4 Pro
 */

const NARRATION_SCRIPTS = [
  {
    id: "intro",
    text: "Welcome. The naive agent sometimes skips customer verification. In production, this leads to 12 percent failure rate.",
    selector: "#scene1-title",
    durationMs: 6000,
  },
  {
    id: "naive-intro",
    text: "The anti-pattern: lookup_order runs without a verified customer ID.",
    selector: "#scene2-naive-intro",
    durationMs: 5000,
  },
  {
    id: "naive-fail",
    text: "Without a verified ID, the wrong account is charged. Red flash. System compromised.",
    selector: "#scene2-naive-fail",
    durationMs: 5000,
  },
  {
    id: "resilient-intro",
    text: "The resilient architecture enforces a strict programmatic prerequisite.",
    selector: "#scene3-resilient-intro",
    durationMs: 5000,
  },
  {
    id: "resilient-pillars",
    text: "Three pillars: context fork, input validation, and shield blocking.",
    selector: "#scene3-pillars",
    durationMs: 6000,
  },
  {
    id: "resilient-success",
    text: "With a verified ID, the correct account is always used. Green flash. Guard activated.",
    selector: "#scene3-success",
    durationMs: 5000,
  },
  {
    id: "metrics",
    text: "Results: token reduction, zero blocked destructive actions, success rate maxed.",
    selector: "#scene4-metrics",
    durationMs: 8000,
  },
  {
    id: "outro",
    text: "Programmatic prerequisites beat prompt-based guardrails. Build reliable AI agents.",
    selector: "#scene4-outro",
    durationMs: 6000,
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { NARRATION_SCRIPTS };
}
